uvmf:
  environments:
    decode:
      agents:
      - initiator_responder: INITIATOR
        name: decode_in_agent_obj
        type: decode_in
      - initiator_responder: RESPONDER
        name: decode_out_agent_obj
        type: decode_out
      analysis_components:
      - name: predictor
        parameters: []
        type: decode_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: decode_out_transaction
      subenvs: []
      tlm_connections:
      - driver: decode_in_agent_obj.monitored_ap
        receiver: predictor.analysis_export
        validate: 'True'
      - driver: predictor.predictor_analysis_port
        receiver: scoreboard.expected_analysis_export
        validate: 'True'
      - driver: decode_out_agent_obj.monitored_ap
        receiver: scoreboard.actual_analysis_export
        validate: 'True'
