uvmf:
  environments:
    fetch:
      agents:     
      - name: fetch_in_agent
        type: "fetch_in"
        initiator_responder: INITIATOR
      - name: fetch_out_agent
        type: fetch_out
        initiator_responder: RESPONDER 
        
      analysis_components:
      - name: "predictor"
        type: "fetch_predictor"
      imports:
      - name: fetch_in_pkg
      - name: fetch_out_pkg  
      - name: lc3_prediction_pkg
      
      scoreboards:
      - name: "fetch_scoreboard"
        sb_type: "uvmf_in_order_race_scoreboard"
        trans_type: "fetch_out_transaction"
        
      tlm_connections:
      - driver: "fetch_in_agent.monitored_ap"
        receiver: "predictor.analysis_export"
          
      - driver: "predictor.analysis_port"
        receiver: "fetch_scoreboard.expected_analysis_export"
        
      - driver: "fetch_out_agent.monitored_ap"
        receiver: "fetch_scoreboard.actual_analysis_export"   



