uvmf:
  environments:
    writeback:
      agents:
      - initiator_responder: INITIATOR
        name: writeback_in_my_agent
        type: writeback_in
      - initiator_responder: RESPONDER
        name: writeback_out_my_agent
        type: writeback_out
      analysis_components:
      - name: writeback_my_predictor
        parameters: []
        type: writeback_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: writeback_my_scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: writeback_out_transaction
      subenvs: []
      tlm_connections:
      - driver: writeback_in_my_agent.monitored_ap
        receiver: writeback_my_predictor.analysis_export
        validate: 'True'
      - driver: writeback_my_predictor.analysis_port
        receiver: writeback_my_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: writeback_out_my_agent.monitored_ap
        receiver: writeback_my_scoreboard.actual_analysis_export
        validate: 'True'
