uvmf:
  environments:
    execute:
      agents:
      - initiator_responder: INITIATOR
        name: in_agt
        type: execute_in
      - initiator_responder: RESPONDER
        name: out_agt
        type: execute_out
      analysis_components:
      - name: pred
        parameters: []
        type: execute_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: scbd
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: execute_out_transaction
      subenvs: []
      tlm_connections:
      - driver: in_agt.monitored_ap
        receiver: pred.analysis_export
        validate: 'True'
      - driver: pred.analysis_port
        receiver: scbd.expected_analysis_export
        validate: 'True'
      - driver: out_agt.monitored_ap
        receiver: scbd.actual_analysis_export
        validate: 'True'
